theme: jekyll-theme-minimal

title: TRADESPACE UNIVERSE
description: This is a final-project page for MIT 6.859 (Interactive Data Visualization) by Akshit Singla taken during Spring'21.

logo: https://scontent-bos3-1.xx.fbcdn.net/v/t1.18169-9/10612670_10152670214585867_7511135003137892386_n.png?_nc_cat=105&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=3Bk-aVzdN3AAX_GQ-WF&_nc_ht=scontent-bos3-1.xx&oh=40d93325676b1d5437861aa14bad1fde&oe=60CCBFD4